name: freud_ai
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.4.2

  ## Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  ## Flutter Bloc and Provider
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  #DotEnv for hiding the API Keys
  flutter_dotenv: ^5.1.0


  # for background services
  flutter_background_service: ^5.0.6
  workmanager: ^0.5.2


  ## Svg Pictures
  flutter_svg: ^2.0.9

  ## Graphs and Sliders
  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_charts: ^26.2.7
  syncfusion_flutter_sliders: ^26.2.7
  dashed_circular_progress_bar: ^0.0.6
  fl_chart: ^0.68.0


  ##Bottom Navigation Bar
#  curved_labeled_navigation_bar: ^2.0.2


  ##Lottie Animations
  lottie: ^3.1.2



  ## Intl for formatting
  intl: ^0.19.0
  timezone: ^0.9.2


  ## Calenders
  table_calendar: ^3.0.9   #for monthly views calender
  easy_date_timeline: ^1.1.3
  syncfusion_flutter_datepicker: ^26.2.7 # for range picker



  ## Dotted Line
  dotted_line: ^3.2.2
  flutter_launcher_icons: ^0.13.1



  ## Animation for column and ListViews
  flutter_staggered_animations: ^1.1.1



  # share prefs and SQflite for Local Database
  shared_preferences: ^2.3.1
  sqflite: ^2.3.0
  path: ^1.8.0


  ## For OpenAI APIs
  chat_gpt_flutter: ^1.0.16



  ##Speech to text
  speech_to_text: ^6.4.1



  #Step Counter
  pedometer: ^4.0.1
#  sensors_plus: 3.1.0
  vibration: ^1.8.4


  #permission
  permission_handler: ^11.3.1


  #Local Notifications
  flutter_local_notifications: ^17.2.1+2
  rxdart: ^0.28.0
  # this package is only use for generation notification id, in DailyRoutinePlannerDataResource file
  # in generateNotificationId function
  crypto: ^3.0.3


  #For launch Urls
  url_launcher: ^6.2.5

  #Share APP
  share_plus: ^10.0.0

  
  #for Alarm
#  alarm: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/main/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/emoji/
    - assets/splash/
    - assets/welcome/
    - assets/home/
    - assets/common/
    - assets/signin/
    - assets/assessment/
    - assets/profile/
    - assets/mood/
    - assets/bmi/
    - assets/sleep/
    - assets/steps/
    - assets/routine/
    - assets/ai/
    - assets/questions/
    - assets/new/
    - .env

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800